server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server7002
eureka:
  instance:
    hostname: eureka7002 #指定主机地址
    prefer-ip-address: true
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka
  server:
    enable-self-preservation: false #关闭保护模式