server:
  port: 9001
spring:
  application:
    name: cloud-nacos-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.133.10:8848 # 配置nacos注册中心的地址
logging:
  config: classpath:log4j2.xml # 配置log4j2的配置文件 ，默认就是log4j2.xml