server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka7001 #指定主机地址
    prefer-ip-address: true
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://eureka7003:7003/eureka,http://eureka7002:7002/eureka
  server:
    enable-self-preservation: false #关闭保护模式
logging:
  config: classpath:log4j2.xml # 配置log4j2的配置文件 ，默认就是log4j2.xml